### ISSUE TITLE
求助:编译困难

### ISSUE THREAD

**Issue by warm-dawn** [kbengine/kbengine_ogre_demo#2]
![image](https://user-images.githubusercontent.com/59309812/111542489-c5f19280-87ac-11eb-9f53-86afd8b7643d.png)
编译遇到困难
_ssl.pyd 在目录: kbengine_ogre_demo-1.1.5\kbengine\kbe\res\scripts\common\DLLs\_ssl.pyd
如果我把它拷贝到../../libs 它将会发生读取错误.

kbengine.lib 不存在

VS2019

**Comment by kebiao** [comment]
用unity和ue4 demo吧， 这个ogre太老了
